name: MLflow Training CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "ci_outputs/**"
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    # =============================
    # CHECKOUT
    # =============================
    - name: Checkout repo
      uses: actions/checkout@v4

    # =============================
    # PYTHON
    # =============================
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    # =============================
    # DEPENDENCIES
    # =============================
    - name: Install dependencies
      run: |
        pip install mlflow==2.19.0 dagshub scikit-learn pandas matplotlib seaborn

    # =============================
    # MLFLOW + DAGSHUB ENV
    # =============================
    - name: Set MLflow (DagsHub) Environment
      run: |
        echo "MLFLOW_TRACKING_URI=https://dagshub.com/zakialfadilah/loan-prediction-mlflow.mlflow" >> $GITHUB_ENV
        echo "MLFLOW_TRACKING_USERNAME=${{ secrets.DAGSHUB_USER }}" >> $GITHUB_ENV
        echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

    # =============================
    # RUN TRAINING (AUTOLOG ENABLED)
    # =============================
    - name: Run modelling script (with autolog)
      run: |
        python MLProject/modelling.py

    # =============================
    # SAVE TRAINING OUTPUT (MID PIPELINE)
    # =============================
    - name: Upload MLflow artifacts (GitHub Evidence)
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-training-artifacts
        path: |
          mlruns/
          MLProject/preprocessing/LoanPrediction_preprocessing.csv

    # =============================
    # BUILD DOCKER MODEL (REQUIRED STEP)
    # =============================
    - name: Build Docker Image from Production Model
      run: |
        mlflow models build-docker \
          --model-uri models:/LoanPredictionModel@production \
          --name zakialfadilah/loan-prediction-mlflow

    # =============================
    # DOCKER HUB LOGIN
    # =============================
    - name: Login Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # =============================
    # PUSH IMAGE
    # =============================
    - name: Push Docker Image
      run: |
        docker push zakialfadilah/loan-prediction-mlflow
